openapi: 3.0.0
info:
  title: Book Management API
  description: This is a simple API for managing books with CRUD operations.
  version: "1.0.0"
servers:
  - url: "http://localhost:3000/"
    description: Local server
paths:
  /books:
    get:
      summary: Get a list of all books
      responses:
        "200":
          description: A list of books.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Book"
    post:
      summary: Add a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
      responses:
        "201":
          description: Book created
  /books/{bookId}:
    get:
      summary: Get a book by ID
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A single book.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
    put:
      summary: Update a book by ID
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Book"
      responses:
        "200":
          description: Book updated
    delete:
      summary: Delete a book by ID
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Book deleted

components:
  schemas:
    Book:
      type: object
      required:
        - title
        - author
        - summary
      properties:
        title:
          type: string
          example: "The Great Gatsby"
        author:
          type: string
          example: "F. Scott Fitzgerald"
        summary:
          type: string
          example: "The book is a story about love, wealth, and life during the Roaring 20s."
